const samples = [
    `One advantage of the five-paragraph model is that it structures what I write. Before I learned the five-paragraph recipe, I'd either stare at a blank screen or I'd write one big block of text; now, I know to first identify three examples, reasons, or other supporting pieces of evidence. Then, I develop those three examples, reasons, or pieces of evidence into its own paragraph. I write a thesis statement based off those three examples, reasons, or pieces of evidence; I flesh out my introduction with a hook; and I write a conclusion paragraph. Following the five-paragraph model makes my writing tasks considerably less intimidating.`,

    `The Pomodoro Technique is a time management method developed by Francesco Cirillo in the late 1980s. It uses a kitchen timer to break work into intervals, typically 25 minutes in length, separated by short breaks. Each interval is known as a pomodoro, from the Italian word for tomato, after the tomato-shaped kitchen timer Cirillo used as a university student. Apps and websites providing timers and instructions have widely popularized the technique. Closely related to concepts such as timeboxing and iterative and incremental development used in software design, the method has been adopted in pair programming contexts.`,

    `Pokemon is a Japanese media franchise consisting of video games, animated series and films, a trading card game, and other related media. The franchise takes place in a shared universe in which humans co-exist with creatures known as Pokemon, a large variety of species endowed with special powers. The franchise's target audience is children aged 5 to 12, but it is known to attract people of all ages. The franchise originated as a pair of role-playing games developed by Game Freak, following an original concept by its founder, Satoshi Tajiri. Released on the Game Boy on February 27, 1996, the games became sleeper hits and were followed by manga series, a trading card game, and anime series and films. From 1998 to 2000, Pokemon was exported to the rest of the world, creating an unprecedented global phenomenon dubbed "Pokemania". By 2002, the craze had ended, after which Pokemon became a fixture in popular culture, with new products being released to this day. In the summer of 2016, the franchise spawned a second craze with the release of Pokemon Go, an augmented reality game developed by Niantic. Pokemon has since been estimated to be the world's highest-grossing media franchise and one of the best-selling video game franchises.`,

    `We always see the same side of the Moon, because as Earth's natural satellite revolves around our planet, the Moon rotates, causing the same side to always face us. And yet, the Moon looks a little different every night. Sometimes the entire face glows brightly. Sometimes we only see a thin crescent. Other times the Moon seems to disappear entirely. Why does the Moon's appearance change? The moonlight we see on Earth is sunlight reflected off the Moon's grayish-white surface. The amount of Moon we see illuminated changes over the month — lunar phases — because the Moon orbits Earth and Earth orbits the Sun. Everything is moving. Our Moon doesn't shine, it reflects sunlight. Just as it does in the daytime on Earth, sunlight illuminates the Moon's surface too. That is, the Moon has a day side and also a night side. And as the Moon orbits Earth each month, we do not have a continuous view of the entire side of the Moon that's facing the Sun. Most of the time, our view of the Moon looks toward part of the sunlit side and part of the dark side at the same time.`,
    
    `In contemporary music production, an '808' refers to a percussion sound known for its booming, low-frequency bass, famously popularized by the TR-808's bass drum, often called the '808 kick.' This iconic sound has become a cornerstone in various music genres, notably in hip-hop, trap, and electronic dance music. Producers and musicians frequently rely on 808 kick samples or emulations to craft impactful and sub-heavy basslines in their tracks. At first listen, the 808 blurs the distinction between a kick and a bass. So, which is it? In practice, the 808 is used in music as both a kick and a bass. By extending the decay, sustain, and release times of an 808 and aligning its pitch with your track's key, the 808 serves as both the kick drum and the bass line of a beat, enhancing both rhythmic energy and providing a robust low-end foundation in your music. In some instances, a kick drum and a bass sound are layered together to create the sound of an 808.`,

    `When thinking about getting the sleep you need, it is normal to focus on how many hours of sleep you get. While sleep duration is undoubtedly important, it is not the only part of the equation. It is also critical to think about sleep quality and whether the time spent sleeping is actually restorative. Progressing smoothly multiple times through the sleep cycle, composed of four separate sleep stages, is a vital part of getting high-quality rest. Each sleep stage plays a part in allowing the mind and body to wake up refreshed. Understanding the sleep cycle also helps explain how certain sleep disorders, including insomnia and obstructive sleep apnea, can impact a person’s sleep and health. Sleep is not uniform. Instead, over the course of the night, your total sleep is made up of several rounds of the sleep cycle, which is composed of four individual stages. In a typical night, a person goes through four to six sleep cycles. Not all sleep cycles are the same length, but on average they last about 90 minutes each.`,

    `The great Kobe Bryant was an athlete of the first degree. He was one of basketball’s most accomplished shooting guards and played 20 seasons with the Los Angeles Lakers, which comprised his entire athletic career right out of high school. He could arguably be considered the sport’s GOAT (greatest of all time). Of course, the debate over the professional basketball GOAT is decades-long, but whether you believe it’s Kobe Bryant, Michael Jordan, LeBron James, Larry Bird, Magic Johnson, Kareem Abdul-Jabbar or any of the other b-ball greats, they all got there because they put their entire heart into each game. Similarly, when you make the decision to do whatever you've chosen to do, whether in life or in business, it's important to devote ever-increasing amounts of energy to that single idea. Believe that failure is not an option. This can often be the difference between making a modest achievement of your idea and turning it into the GOAT in business.`,

    `Meditation, often thought of as a path to self-awareness and compassion, can also be a path to better health. Practiced for thousands of years in Hindu, Buddhist, Zen/Chan and Taoist communities, people use meditation today to cope with stress and worry in a busy world. It can help bring calm and insight to people who often feel anxious. Meditation refers to a set of techniques to enhance attention, emotional awareness, kindness, compassion, sympathetic joy, and mental calmness even in difficult situations. Some people find that regular meditation practice helps them be kind to themselves and more caring towards others. It can also teach you to be a little less reactive when tough situations arise. There are hundreds of different meditation techniques that vary from simple to more complex. It’s best to start with a simple practice that you can work into your regular routine over time. You can do this daily at the same time, even if it’s just a few minutes to start out. Over time, you will build discipline and skill with practice.`



]

export default samples;